# Generated by Django 5.2.6 on 2025-10-03 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_free',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('venmo', 'Venmo'), ('zelle', 'Zelle'), ('cash', 'Cash')], max_length=20),
        ),
        migrations.AddField(
            model_name='post',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
